// Generated by Wrangler by running `wrangler types`

interface Env {
	SUDOS: KVNamespace;
	NETWORK_PASSPHRASE: string;
	MOCK_SK: string;
	NATIVE_CONTRACT_ID: string;
	FUND_SK: string;
	JWT_SECRET: string;
	ENV: string;
	CREDITS_DURABLE_OBJECT: DurableObjectNamespace;
	SEQUENCER_DURABLE_OBJECT: DurableObjectNamespace;
	DB: D1Database;
}
