// Generated by Wrangler by running `wrangler types`

interface Env {
	SUDOS: KVNamespace;
	CODES: KVNamespace;
	ENV: string;
	NETWORK_PASSPHRASE: string;
	NATIVE_CONTRACT_ID: string;
	RPC_URLS: string;
	MOCK_SK: string;
	FUND_SK: string;
	JWT_SECRET: string;
	CREDITS_DURABLE_OBJECT: DurableObjectNamespace<import("./dist/index").CreditsDurableObject>;
	SEQUENCER_DURABLE_OBJECT: DurableObjectNamespace<import("./dist/index").SequencerDurableObject>;
	DB: D1Database;
}
