#:schema node_modules/wrangler/config-schema.json
name = "launchtube"
main = "dist/index.js"
compatibility_date = "2025-10-03"
workers_dev = false
minify = true
logpush = false
send_email = [
    { name = "EMAIL" }
]

[observability.logs]
enabled = true
invocation_logs = false

[build]
command = "npm run build"

[[migrations]]
tag = "v1"
new_classes = ["CreditsDurableObject", "SequencerDurableObject"]

[[migrations]]
tag = "v2"
new_classes = ["MonitorDurableObject"]

[triggers]
crons = [ "*/5 * * * *" ]

### DEV ###

[[durable_objects.bindings]]
name = "CREDITS_DURABLE_OBJECT"
class_name = "CreditsDurableObject"

[[durable_objects.bindings]]
name = "SEQUENCER_DURABLE_OBJECT"
class_name = "SequencerDurableObject"

[[durable_objects.bindings]]
name = "MONITOR_DURABLE_OBJECT"
class_name = "MonitorDurableObject"

[[kv_namespaces]]
binding = "SUDOS"
id = "1fcab4e76e4948ba9b728271fa51586d"

[[kv_namespaces]]
binding = "CODES"
id = "1717f596858e4685b9b77b0ac047c2b5"

[define]
global = "globalThis"

[vars]
ENV = "development"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
NATIVE_CONTRACT_ID = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC"

### PROD ###

[env.prod]
workers_dev = false
send_email = [
    { name = "EMAIL" }
]

[[env.prod.durable_objects.bindings]]
name = "CREDITS_DURABLE_OBJECT"
class_name = "CreditsDurableObject"

[[env.prod.durable_objects.bindings]]
name = "SEQUENCER_DURABLE_OBJECT"
class_name = "SequencerDurableObject"

[[env.prod.durable_objects.bindings]]
name = "MONITOR_DURABLE_OBJECT"
class_name = "MonitorDurableObject"

[[env.prod.kv_namespaces]]
binding = "SUDOS"
id = "4d86c63ffe344460ab9f740c48e01cab"

[[env.prod.kv_namespaces]]
binding = "CODES"
id = "522dc827cd9f43e58a2810d974fb80c3"

[env.prod.define]
global = "globalThis"

[env.prod.vars]
ENV = "production"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
NATIVE_CONTRACT_ID = "CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA"

### FUTURENET ###

[env.futurenet]
workers_dev = false
send_email = [
    { name = "EMAIL" }
]

[[env.futurenet.durable_objects.bindings]]
name = "CREDITS_DURABLE_OBJECT"
class_name = "CreditsDurableObject"

[[env.futurenet.durable_objects.bindings]]
name = "SEQUENCER_DURABLE_OBJECT"
class_name = "SequencerDurableObject"

[[env.futurenet.durable_objects.bindings]]
name = "MONITOR_DURABLE_OBJECT"
class_name = "MonitorDurableObject"

[[env.futurenet.kv_namespaces]]
binding = "SUDOS"
id = "3c556bb051754cea8d3a68037bc6e0b5"

[[env.futurenet.kv_namespaces]]
binding = "CODES"
id = "f91408337b7c4adca251f8a371f0ac72"

[env.futurenet.define]
global = "globalThis"

[env.futurenet.vars]
ENV = "development"
NETWORK_PASSPHRASE = "Test SDF Future Network ; October 2022"
NATIVE_CONTRACT_ID = "CB64D3G7SM2RTH6JSGG34DDTFTQ5CFDKVDZJZSODMCX4NJ2HV2KN7OHT"