#:schema node_modules/wrangler/config-schema.json
name = "launchtube"
main = "dist/index.js"
compatibility_date = "2024-05-12"
workers_dev = true
minify = true

[build]
command = "npm run build"

[[migrations]]
tag = "v1"
new_classes = ["CreditsDurableObject", "SequencerDurableObject"]

### DEV ###

[[durable_objects.bindings]]
name = "CREDITS_DURABLE_OBJECT"
class_name = "CreditsDurableObject"

[[durable_objects.bindings]]
name = "SEQUENCER_DURABLE_OBJECT"
class_name = "SequencerDurableObject"

[[kv_namespaces]]
binding = "SUDOS"
id = "1fcab4e76e4948ba9b728271fa51586d"

[[kv_namespaces]]
binding = "CODES"
id = "1717f596858e4685b9b77b0ac047c2b5"

[[d1_databases]]
binding = "DB"
database_name = "launchtube-testnet"
database_id = "80e789b8-41a6-4741-aeca-62b4203661dc"

[define]
global = "globalThis"

[vars]
ENV = "development"
RPC_URLS = '["https://soroban-testnet.stellar.org"]'
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"
NATIVE_CONTRACT_ID = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC"
MOCK_SK = "SCOXOZQWWXRJJYXWOHY4DYDH5KXMELFBIMRPPRBYHBV23SQO2KM3NSXZ"

### PROD ###

[env.prod]
workers_dev = false

[[env.prod.durable_objects.bindings]]
name = "CREDITS_DURABLE_OBJECT"
class_name = "CreditsDurableObject"

[[env.prod.durable_objects.bindings]]
name = "SEQUENCER_DURABLE_OBJECT"
class_name = "SequencerDurableObject"

[[env.prod.kv_namespaces]]
binding = "SUDOS"
id = "4d86c63ffe344460ab9f740c48e01cab"

[[env.prod.kv_namespaces]]
binding = "CODES"
id = "522dc827cd9f43e58a2810d974fb80c3"

[[env.prod.d1_databases]]
binding = "DB"
database_name = "launchtube-public"
database_id = "22bd71e0-81f5-4d93-80a9-1242869cbbe5"

[env.prod.define]
global = "globalThis"

[env.prod.vars]
ENV = "production"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"
NATIVE_CONTRACT_ID = "CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA"